### ISSUE TITLE
standardize cache dir setting

### ISSUE THREAD

**Issue by nsheff** [waldronlab/bedbaser#3]
Two suggestions on cache dir:

1. I like the ability to configure via env var. Should we use the same env var for the python client? we're using `BBCLIENT_CACHE`. Maybe just standardize both packages on `BEDBASE_CACHE`?
2. It would be nice to be able to configure the cache dir without an env var, if desired. maybe parameterize it through the constructor `api = BEDbase(cache_dir="...")`? This way I could have 2 apis pointing at different services, for instance, or maybe I don't want to or cant set an env var for some reason.

**Comment by jwokaty** [comment]
Great suggestions, thanks!

**Comment by sanghoonio** [comment]
Is it worth adding an export function so you can save the bed files from a bed ID or bedset to a directory of your choice? Or maybe you could include `cache_dir` as a param for `bb_to_granges/list()` so you can set where the bed files are saved individually?

**Comment by jwokaty** [comment]
@sanghoonio Is this separate from the cache? For example, a user wants to download the bed files to their home directory to process in another way? I think it should be separate from creating a `GRanges` object.

**Comment by sanghoonio** [comment]
Yes, having a separate download function with a `save_dir` param would probably make more sense. An example I am working on right now would be using bedbaser to download a local region set database consisting of bed files from several bedsets to a project directory. Updating the cache dir still works for this but having a dedicated download function would be better.
