### ISSUE TITLE
Include BED overview info in bb_metadata()?

### ISSUE THREAD

**Issue by sanghoonio** [waldronlab/bedbaser#8]
I noticed that the overview details for a BED file aren't included in the `bb_metadata()` output. It would great if I could retrieve this info with bedbaser:

```
> bb_metadata(api, '5b2a96eab4a242363e15fb4f59e661f6')
$name
[1] "wgEncodeAwgTfbsBroadDnd41CtcfUniPk"

$genome_alias
[1] "hg38"

$genome_digest
NULL

$bed_type
[1] "bed3+0"

$bed_format
[1] "bed"

$id
[1] "5b2a96eab4a242363e15fb4f59e661f6"

$description
NULL

$submission_date
[1] "2024-04-12T01:00:57.596157Z"

$last_update_date
[1] "2024-04-12T01:00:57.596160Z"

$is_universe
[1] FALSE

$license_id
[1] "DUO:0000042"

$stats
NULL

$plots
NULL

$files
NULL

$universe_metadata
NULL

$raw_metadata
NULL

$bedsets
list()
```

<img width="651" alt="image" src="https://github.com/user-attachments/assets/61495d9a-1ce3-45c1-8ac2-50fa7444e5a8">

**Comment by jwokaty** [comment]
I can see this information when I request the full metadata with `bb_metadata(api, '5b2a96eab4a242363e15fb4f59e661f6', TRUE)`. `full = FALSE` by default following the API: https://api.bedbase.org/v1/docs#/bed/get_bed_metadata_v1_bed__bed_id__metadata_get. Should I present it in a different way?

**Comment by sanghoonio** [comment]
Sorry, didn't see the full param. I'll close this issue.
