### ISSUE TITLE
Initialization feedback for user

### ISSUE THREAD

**Issue by nsheff** [waldronlab/bedbaser#9]
Right now, when you initialize an API client, the response is silent:

```
api <- BEDbase()
```

Instead, I suggest printing out some information. You could get some from the `/service-info` endpoint contents.

https://api.bedbase.org/v1/service-info

Maybe just showing "Connected" and the version, or you could show "6585 BED files available" or something like that.

You can get the count from this endpoint: `https://api.bedbase.org/v1/bed/list?limit=0&offset=0`

Just some visual cue to show the connection was successful.

**Comment by jwokaty** [comment]
[0.99.12](https://github.com/waldronlab/bedbaser/pull/14) reports available bed files:

```
> library(bedbaser)
> api <- BEDbase()
19974 BED files available.
```

Thanks for this great suggestion!
